Initial symbol bootstrap 0.9.7.0
nemtech/symbol-bootstrap pull request #15
Opened 2020-09-10 11:44 UTC by fboucquez

2020-09-21 14:25 UTC, segfaultxavi requested changes

2020-09-21 14:25 UTC, segfaultxavi commented on CHANGELOG.md
> +**Milestone**: Gorilla.1(0.9.7.0)
Shouldn't this version number be `0.10.0.1`?

2020-09-21 14:25 UTC, segfaultxavi commented on CHANGELOG.md
> +- 0.9.7.0 server support.
Same as above.

2020-09-26 11:45 UTC, fboucquez commented
@segfaultxavi I've fixed the comments. Thanks. Are we happy to squash merge this PR @Wayonb @rg911?

2020-09-26 11:58 UTC, merged