Mainnet unfinalized blocks duration
nemtech/symbol-bootstrap pull request #196
Opened 2021-03-17 13:30 UTC by fboucquez

2021-03-17 13:40 UTC, Wayonb requested changes

2021-03-17 13:40 UTC, Wayonb commented on presets/mainnet/network.yml
> +unfinalizedBlocksDuration: 10m
Is this only for non voting nodes?

2021-03-17 14:18 UTC, fboucquez commented on presets/mainnet/network.yml
> +unfinalizedBlocksDuration: 10m
Added custom value for voting nodes

2021-03-17 14:36 UTC, Wayonb requested changes

2021-03-17 14:36 UTC, Wayonb commented on presets/mainnet/network.yml
> +votingUnfinalizedBlocksDuration: 10m
should probably be votingUnfinalizedBlocksDuration => nonVotingUnfinalizedBlocksDuration?

2021-03-17 14:36 UTC, Wayonb commented on src/service/ConfigService.ts
> +            unfinalizedBlocksDuration: nodePreset.voting
should be the reverse?

2021-03-17 18:57 UTC, fboucquez commented on src/service/ConfigService.ts
> +            unfinalizedBlocksDuration: nodePreset.voting
it was fine, now it's clearer

2021-03-18 11:20 UTC, Wayonb requested changes

2021-03-18 11:20 UTC, Wayonb commented on presets/shared.yml
> +votingUnfinalizedBlocksDuration: 8m
When the node is voting - votingUnfinalizedBlocksDuration: 0m
Nonvoting node - nonVotingUnfinalizedBlocksDuration: 8m

2021-03-18 11:20 UTC, Wayonb commented on presets/mainnet/network.yml
> +votingUnfinalizedBlocksDuration: 10m
When the node is voting - votingUnfinalizedBlocksDuration: 0m
Nonvoting node - nonVotingUnfinalizedBlocksDuration: 10m

2021-03-18 13:19 UTC, rg911 approved these changes

2021-03-18 18:13 UTC, Wayonb approved these changes

2021-03-18 18:15 UTC, merged