Initial 0.10.0.4 upgrade
nemtech/symbol-bootstrap pull request #72
Opened 2020-11-13 02:24 UTC by Wayonb

The initial 0.10.0.4 release with preset updated.  
Voting will not work until TS sdk is updated with the latest voting key changes.

2020-11-17 14:05 UTC, fboucquez requested changes

2020-11-17 14:05 UTC, fboucquez commented on config/node/resources/config-finalization.properties.mustache
> +unfinalizedBlocksDuration = 0m
move value to shared.yml

2020-11-17 14:05 UTC, fboucquez commented on config/node/resources/config-messaging.properties.mustache
> +listenInterface = 0.0.0.0
move value to shared.yml

2020-11-17 14:05 UTC, fboucquez commented on config/node/resources/config-node.properties.mustache
> +listenInterface = 0.0.0.0
move value to shared.yml

2020-11-17 14:05 UTC, fboucquez commented on config/node/resources/config-node.properties.mustache
> +version = 0.10.0.4
move value to shared.yml

2020-11-17 14:06 UTC, fboucquez commented
Thanks @Wayonb , ideally we should have all the values in the shared.yml by default. If a value is variable enough to be in a property file, it should be variable enough to be in shared.yml so node admin can change it with custom presets.

2020-11-17 14:08 UTC, fboucquez commented on config/node/resources/config-messaging.properties.mustache
> +listenInterface = 0.0.0.0
unsure if this is shared value with the one in config-node or not. If this value could be different, add a prefix to listenInterface like `messaginListenInterface` and `nodeListenInterface`

2020-11-21 14:37 UTC, Wayonb commented
@fboucquez Thanks for the feedback and fixes.  I fixed the tests :)

2020-11-27 13:22 UTC, merged